const {chromium}=require(process.env.ZHIXU_PLAYWRIGHT_MODULE || 'playwright');
const assert=require('node:assert/strict');
const fs=require('node:fs/promises');
const path=require('node:path');
(async()=>{
  const browser=await chromium.launch({headless:true,channel:process.env.ZHIXU_BROWSER_CHANNEL || 'chrome'});
  const context=await browser.newContext({viewport:{width:1680,height:1180}});
  const page=await context.newPage();
  const errors=[];page.on('pageerror',e=>errors.push(e.message));page.on('dialog',d=>d.accept());
  const base=process.env.ZHIXU_BROWSER_ORIGIN || 'http://127.0.0.1:8788';
  assert.ok(['127.0.0.1','localhost'].includes(new URL(base).hostname),'Browser checks require a local synthetic fixture');
  const artifactDir=path.resolve(process.env.ZHIXU_BROWSER_ARTIFACTS || 'output/playwright');
  await fs.mkdir(artifactDir,{recursive:true});
  try {
    const fixture=await context.request.get(base+'/__test__/fixture');
    assert.ok(fixture.ok(),'Start tests/browser/preview.py before browser acceptance');
    assert.equal((await fixture.json()).fixture,'zhixu-browser-synthetic');
    const registration=await context.request.post(base+'/api/v1/auth/register',{data:{email:`browser-${Date.now()}@example.test`,password:'Synthetic-only-test-password!',organization_name:'Parser acceptance workspace'}});
    assert.equal(registration.status(),201,await registration.text());
    const identity=await (await context.request.get(base+'/api/v1/auth/me')).json();
    const headers={'X-Workspace-ID':identity.organizations[0].id,'X-CSRF-Token':identity.csrf_token};
    const request=async(url,data)=>{const response=await context.request.post(base+url,{headers,data});assert.ok(response.ok(),await response.text());return response.json();};
    const kb=await request('/api/v1/knowledge-bases',{name:'Synthetic warranty knowledge',description:'Disposable browser acceptance documents'});
    const upload=await context.request.post(base+`/api/v1/kb/${kb.id}/documents`,{headers,multipart:{files:{name:'synthetic-warranty.txt',mimeType:'text/plain',buffer:Buffer.from('Standard warranty lasts 12 months. Repair requires proof of purchase.')}}});
    assert.ok(upload.ok(),await upload.text());
    const doc=(await upload.json()).documents[0];
    for(let n=0;n<60;n++){
      const documents=await (await context.request.get(base+`/api/v1/kb/${kb.id}/documents`,{headers})).json();
      if(documents.items.find(item=>item.id===doc.id)?.status==='completed')break;
      if(n===59)throw new Error('Import did not complete');
      await new Promise(resolve=>setTimeout(resolve,200));
    }
    await page.goto(base+'/?lang=en#knowledge');
    await page.locator('#editKB').waitFor();
    assert.equal(await page.locator('.brand strong').textContent(),'Zhixu');
    assert.equal(await page.locator('[data-nav="billing"]').count(),0);
    await page.locator('#editKB').click();
    await page.locator('dialog select[name=parser_mode]').selectOption('native');
    await page.locator('dialog select[name=text_encoding]').selectOption('gb18030');
    await page.locator('dialog input[name=max_rows]').fill('100');
    assert.equal(await page.locator('dialog select[name=kb_type] option:checked').textContent(),'General documents');
    await page.screenshot({path:path.join(artifactDir,'parser-settings.jpg'),fullPage:true});
    await page.locator('dialog button[type=submit]').click();
    await page.locator('dialog').waitFor({state:'hidden'});
    const settings=await (await context.request.get(base+`/api/v1/knowledge-bases/${kb.id}`,{headers})).json();
    assert.deepEqual(settings.parser_config,{mode:'native',text_encoding:'gb18030',max_rows:100});
    await page.locator('[data-nav=workflows]').click();
    await page.locator('#graphCanvas').waitFor();
    console.log('Rendered graph and parser parameters', JSON.stringify({title:await page.title(),errors}));
    await page.locator('.graph-node').filter({hasText:'Knowledge retrieval'}).click();
    await page.locator('#removeNode').click();
    await page.locator('.graph-node').filter({hasText:'Model generation'}).click();
    await page.locator('#removeNode').click();
    await page.locator('[data-type=files]').click();
    const fileHeader=page.locator('.graph-node').filter({hasText:'File evidence'}).locator('.graph-node-header');
    const sourceBox=await fileHeader.boundingBox(),inputBox=await page.locator('.graph-node').filter({hasText:'Question input'}).locator('.graph-node-header').boundingBox();
    const scale=(await page.locator('.graph-node').filter({hasText:'File evidence'}).boundingBox()).width/220;
    await page.mouse.move(sourceBox.x+sourceBox.width/2,sourceBox.y+sourceBox.height/2);
    await page.mouse.down();
    await page.mouse.move(inputBox.x+inputBox.width/2+250*scale,inputBox.y+inputBox.height/2,{steps:12});
    await page.mouse.up();
    assert.ok((await fileHeader.boundingBox()).x<sourceBox.x,'File node moves by dragging');
    await page.locator('#nodeForm select[name=kb_ids]').selectOption(kb.id);
    await page.locator(`#nodeForm select[name=doc_ids] option[value="${doc.id}"]`).waitFor();
    await page.locator('#nodeForm select[name=doc_ids]').selectOption(doc.id);
    await page.locator('#nodeForm button[type=submit]').click();
    await page.locator('.graph-node').filter({hasText:'Question input'}).locator('[data-out]').click();
    await page.locator('.graph-node').filter({hasText:'File evidence'}).locator('[data-in]').click();
    await page.locator('.graph-node').filter({hasText:'File evidence'}).locator('[data-out]').click();
    await page.locator('.graph-node').filter({hasText:'Evidence gate'}).locator('[data-in]').click();
    await page.locator('.graph-node').filter({hasText:'Evidence gate'}).locator('[data-out]').click();
    await page.locator('.graph-node').filter({hasText:'Answer output'}).locator('[data-in]').click();
    assert.equal(await page.locator('.graph-edges path').count(),3,'All workflow connections must be visibly rendered');
    await page.locator('#workflowName').fill('File evidence acceptance');
    await page.locator('#validateGraph').click();
    await page.getByText('Structure, resources and parameters validated',{exact:true}).waitFor();
    await page.locator('#saveGraph').click();
    await page.locator('#draftState').getByText('Draft saved',{exact:true}).waitFor();
    await page.locator('#publishGraph').click();
    await page.locator('#draftState').getByText('Published',{exact:true}).waitFor();
    await page.locator('#publishedRun').check();
    await page.locator('#runForm textarea').fill('What warranty evidence was selected?');
    await page.locator('#runButton').click();
    await page.locator('#runStatus').getByText('Run complete',{exact:true}).waitFor();
    assert.match(await page.locator('#runResult').textContent(),/12 months/);
    assert.ok(await page.locator('#runResult .trace-step').count()>=4);
    await page.getByRole('button',{name:'Fit canvas',exact:true}).click();
    await page.locator('#nodeForm select[name=doc_ids]').selectOption([]);
    await page.locator('#nodeForm button[type=submit]').click();
    await page.locator('.graph-node').filter({hasText:'Evidence gate'}).click();
    await page.locator('.graph-node').filter({hasText:'File evidence'}).click();
    assert.deepEqual(await page.locator('#nodeForm select[name=doc_ids]').evaluate(e=>Array.from(e.selectedOptions).map(o=>o.value)),[]);
    await page.locator('#nodeForm select[name=doc_ids]').selectOption(doc.id);
    await page.locator('#nodeForm button[type=submit]').click();
    await page.locator('#saveGraph').click();
    await page.locator('#draftState').getByText('Draft saved',{exact:true}).waitFor();
    await page.reload();
    await page.locator('#workflowSelect').selectOption({label:'File evidence acceptance'});
    await page.locator('.run-row').click();
    await page.locator('#runStatus').getByText('Run complete',{exact:true}).waitFor();
    await page.locator('.graph-node').filter({hasText:'File evidence'}).click();
    await page.locator(`#nodeForm select[name=doc_ids] option[value="${doc.id}"]`).waitFor();
    assert.deepEqual(await page.locator('#nodeForm select[name=doc_ids]').evaluate(e=>Array.from(e.selectedOptions).map(o=>o.value)),[doc.id]);
    await page.locator('.node-settings').evaluate(e=>e.scrollTop=0);
    await page.screenshot({path:path.join(artifactDir,'workflow.jpg'),fullPage:true});
    await page.locator('[data-nav=settings]').click();
    await page.getByText(/The deployment environment configures the database, file storage, vector index, allowed model hosts/).waitFor();
    await page.locator('#languageControl').selectOption('zh-CN');
    await page.waitForURL(/lang=zh-CN/);
    await page.getByRole('heading',{name:'工作空间设置',exact:true}).waitFor();
    await page.reload();
    assert.equal(await page.locator('#languageControl').inputValue(),'zh-CN');
    await page.setViewportSize({width:390,height:844});
    await page.locator('#mobileMenu').click();
    await page.locator('[data-nav=knowledge]').click();
    await page.locator('#editKB').waitFor();
    console.log('Mobile widths',JSON.stringify(await page.evaluate(()=>({width:innerWidth,scroll:document.documentElement.scrollWidth,overflow:Array.from(document.querySelectorAll('#shell *')).filter(e=>e.getBoundingClientRect().right>innerWidth+1).slice(0,20).map(e=>({tag:e.tagName,id:e.id,cls:e.className,width:e.getBoundingClientRect().width,right:e.getBoundingClientRect().right}))}))));
    await page.screenshot({path:path.join(artifactDir,'mobile-acceptance.jpg'),fullPage:true});
    assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth));
    assert.deepEqual(errors,[]);
    const evidence={date:'2026-10-08',browser:await browser.version(),driver:'Playwright 1.62.1',fixture:'Disposable synthetic workspace',checks:['English branding and removal of commercial navigation','Parser mode, encoding and row limit saved','File workflow drag, visible connections, validation, draft, published run and trace', 'Saved selection and historical run restored after reload','File deselection preserved after reopening node','English deployment settings','Chinese language switch and reload persistence','390px knowledge page without horizontal document overflow'],errors};
    await fs.writeFile(path.join(artifactDir,'browser-acceptance.json'),JSON.stringify(evidence,null,2));
    console.log(JSON.stringify(evidence));
  } finally {await browser.close();}
})().catch(e=>{console.error(e);process.exitCode=1;});
