import {t,html,staticHTML,localizePage,bindLanguageControl,localeURL,getLocale} from './i18n.js';
const returnhtml=html;
import {NODE_TYPES,GraphHistory,connect,removeNode,makeNode} from './graph.js';
import {esc,toast} from './dom.js';

export class GraphCanvas{
  constructor(host,graph,{onSelect=()=>{},onChange=()=>{},editable=true}={}){
    this.host=host;this.editable=editable;this.history=new GraphHistory(graph);this.graph=this.history.current();this.onSelect=onSelect;this.onChange=onChange;this.selected=null;this.pending=null;this.view={x:25,y:30,scale:0.72};this.drag=null;
    host.innerHTML=staticHTML('<div class="graph-space"><svg class="graph-edges" aria-label="模块连线"></svg><div class="graph-nodes"></div></div><div class="canvas-help">拖动节点调整位置 · 拖动空白平移 · 滚轮缩放 · 输出端口连接输入端口</div><div class="canvas-zoom"><button data-zoom="-" aria-label="缩小">−</button><span>72%</span><button data-zoom="+" aria-label="放大">＋</button><button data-fit aria-label="适应画布">⌖</button></div>');
    this.space=host.querySelector('.graph-space');this.svg=host.querySelector('svg');this.nodes=host.querySelector('.graph-nodes');
    this.click=event=>{const edge=event.target.closest('[data-edge]');if(edge){if(this.editable&&confirm(t('删除此连线？'))){this.graph.edges=this.graph.edges.filter(item=>item.id!==edge.dataset.edge);this.commit();this.paint();}return;}const out=event.target.closest('[data-out]');if(out){if(!this.editable)return;this.pending=this.pending===out.dataset.out?null:out.dataset.out;this.paint();return;}const input=event.target.closest('[data-in]');if(input&&this.pending){this.link(this.pending,input.dataset.in);return;}const node=event.target.closest('[data-node]');if(node){this.select(node.dataset.node);return;}const zoom=event.target.closest('[data-zoom]');if(zoom){this.zoom(zoom.dataset.zoom==='+'?1.15:1/1.15);return;}if(event.target.closest('[data-fit]'))this.fit();};
    this.down=event=>{if(event.button!==0||event.target.closest('.canvas-zoom,[data-edge]'))return;const out=event.target.closest('[data-out]');if(out){if(!this.editable)return;this.drag={kind:'link',source:out.dataset.out,x:event.clientX,y:event.clientY};this.pending=out.dataset.out;event.preventDefault();return;}if(event.target.closest('[data-in]'))return;const node=event.target.closest('[data-node]');if(node){const item=this.graph.nodes.find(n=>n.id===node.dataset.node);this.select(item.id);if(!this.editable)return;this.drag={kind:'node',node:item,x:event.clientX,y:event.clientY,start:{...item.position}};}else this.drag={kind:'pan',x:event.clientX,y:event.clientY,start:{...this.view}};event.preventDefault();};
    this.move=event=>{if(!this.drag)return;const dx=event.clientX-this.drag.x,dy=event.clientY-this.drag.y;this.drag.moved=Math.abs(dx)+Math.abs(dy)>4;if(this.drag.kind==='node'){this.drag.node.position={x:Math.round(Math.max(0,Math.min(5000,this.drag.start.x+dx/this.view.scale))),y:Math.round(Math.max(0,Math.min(4000,this.drag.start.y+dy/this.view.scale)))};this.paint();}else if(this.drag.kind==='pan'){this.view.x=this.drag.start.x+dx;this.view.y=this.drag.start.y+dy;this.transform();}};
    this.up=event=>{const drag=this.drag;this.drag=null;if(!drag)return;if(drag.kind==='node'&&drag.moved)this.commit();if(drag.kind==='link'&&drag.moved){const target=document.elementFromPoint(event.clientX,event.clientY)?.closest('[data-in]');if(target)this.link(drag.source,target.dataset.in);}this.paint();};
    this.wheel=event=>{event.preventDefault();const rect=host.getBoundingClientRect();this.zoom(event.deltaY>0?1/1.08:1.08,{x:event.clientX-rect.left,y:event.clientY-rect.top});};
    this.key=event=>{if(!this.editable)return;if(['INPUT','TEXTAREA','SELECT'].includes(event.target.tagName))return;if(event.key==='Delete'&&this.selected){event.preventDefault();this.remove();}if((event.ctrlKey||event.metaKey)&&event.key.toLowerCase()==='z'){event.preventDefault();event.shiftKey?this.redo():this.undo();}};
    host.addEventListener('click',this.click);host.addEventListener('pointerdown',this.down);window.addEventListener('pointermove',this.move);window.addEventListener('pointerup',this.up);host.addEventListener('wheel',this.wheel,{passive:false});host.addEventListener('keydown',this.key);host.tabIndex=0;
    host.ondragover=event=>{if(event.dataTransfer.types.includes('application/x-node-type'))event.preventDefault();};host.ondrop=event=>{event.preventDefault();const type=event.dataTransfer.getData('application/x-node-type');if(!NODE_TYPES[type])return;const rect=host.getBoundingClientRect();this.add(type,{x:(event.clientX-rect.left-this.view.x)/this.view.scale,y:(event.clientY-rect.top-this.view.y)/this.view.scale});};this.paint();
  }
  get(){return structuredClone(this.graph);}
  set(graph){this.graph=structuredClone(graph);this.history=new GraphHistory(graph);this.selected=null;this.pending=null;this.onSelect(null);this.paint();this.fit();this.onChange(this.get());}
  commit(){this.history.push(this.graph);this.onChange(this.get());}
  select(id){this.selected=id;this.paint();this.onSelect(this.graph.nodes.find(n=>n.id===id)||null);}
  update(id,changes){if(!this.editable)return;const node=this.graph.nodes.find(n=>n.id===id);if(!node)return;Object.assign(node,structuredClone(changes));this.commit();this.paint();}
  add(type,position){if(!this.editable)return;if(this.graph.nodes.length>=40){toast(t('最多 40 个节点'),'error');return;}const rect=this.host.getBoundingClientRect();const p=position||{x:(rect.width/2-this.view.x)/this.view.scale,y:(rect.height/2-this.view.y)/this.view.scale};const node=makeNode(type,undefined,Math.max(0,Math.round(p.x)),Math.max(0,Math.round(p.y)));this.graph.nodes.push(node);this.commit();this.select(node.id);}
  remove(){if(!this.editable)return;if(!this.selected)return;this.graph=removeNode(this.graph,this.selected);this.selected=null;this.commit();this.onSelect(null);this.paint();}
  link(source,target){if(!this.editable)return;try{this.graph=connect(this.graph,source,target);this.pending=null;this.commit();this.paint();}catch(error){toast(error.message,'error');}}
  undo(){if(!this.editable)return;this.graph=this.history.undo();this.select(this.graph.nodes.some(n=>n.id===this.selected)?this.selected:null);this.onChange(this.get());}
  redo(){if(!this.editable)return;this.graph=this.history.redo();this.select(this.graph.nodes.some(n=>n.id===this.selected)?this.selected:null);this.onChange(this.get());}
  zoom(factor,anchor){const rect=this.host.getBoundingClientRect();const center=anchor||{x:rect.width/2,y:rect.height/2};const scale=Math.max(0.25,Math.min(1.8,this.view.scale*factor));const ratio=scale/this.view.scale;this.view.x=center.x-(center.x-this.view.x)*ratio;this.view.y=center.y-(center.y-this.view.y)*ratio;this.view.scale=scale;this.transform();}
  fit(){if(!this.graph.nodes.length)return;const xs=this.graph.nodes.map(n=>n.position.x),ys=this.graph.nodes.map(n=>n.position.y);const minX=Math.min(...xs),minY=Math.min(...ys),w=Math.max(...xs)+220-minX,h=Math.max(...ys)+105-minY;const rect=this.host.getBoundingClientRect();this.view.scale=Math.max(0.25,Math.min(1,Math.min((rect.width-80)/w,(rect.height-100)/h)));this.view.x=(rect.width-w*this.view.scale)/2-minX*this.view.scale;this.view.y=(rect.height-h*this.view.scale)/2-minY*this.view.scale;this.transform();}
  transform(){this.space.style.transform=`translate(${this.view.x}px,${this.view.y}px) scale(${this.view.scale})`;this.host.querySelector('.canvas-zoom span').textContent=`${Math.round(this.view.scale*100)}%`;}
  paint(){
    this.nodes.innerHTML=this.graph.nodes.map(node=>{const meta=NODE_TYPES[node.type];return`<article data-node="${esc(node.id)}" class="graph-node ${node.id===this.selected?'selected':''} ${this.pending===node.id?'connecting':''}" style="left:${Number(node.position.x)||0}px;top:${Number(node.position.y)||0}px"><div class="graph-node-header"><span class="node-icon">${meta.icon}</span><strong>${esc(node.label||t(meta.name))}</strong></div><div class="graph-node-detail">${t(meta.name)}${node.type==='retrieval'?html` · ${(node.config.kb_ids||[]).length} 个知识库`:node.type==='model'&&!node.config.profile_id?t(' · 选择模型'):''}</div>${meta.accepts.length?html`<button data-in="${esc(node.id)}" class="node-port port-in" aria-label="连接到 ${esc(node.label||t(meta.name))}"></button>`:''}${meta.output?html`<button data-out="${esc(node.id)}" class="node-port port-out" aria-label="从 ${esc(node.label||t(meta.name))} 连接"></button>`:''}</article>`;}).join('');
    this.svg.innerHTML=this.graph.edges.map(edge=>{const a=this.graph.nodes.find(n=>n.id===edge.source),b=this.graph.nodes.find(n=>n.id===edge.target);if(!a||!b)return'';const x1=a.position.x+220,y1=a.position.y+53,x2=b.position.x,y2=b.position.y+53;const bend=Math.max(80,Math.abs(x2-x1)*0.45);returnhtml`<path data-edge="${esc(edge.id)}" aria-label="删除连线" d="M${x1},${y1} C${x1+bend},${y1} ${x2-bend},${y2} ${x2},${y2}"/>`;}).join('');this.transform();
  }
  dispose(){this.host.removeEventListener('click',this.click);this.host.removeEventListener('pointerdown',this.down);window.removeEventListener('pointermove',this.move);window.removeEventListener('pointerup',this.up);this.host.removeEventListener('wheel',this.wheel);this.host.removeEventListener('keydown',this.key);this.host.ondragover=null;this.host.ondrop=null;}
}
