import {t,html,staticHTML,localizePage,bindLanguageControl,localeURL,getLocale} from './i18n.js';
import {$,esc,toast,showModal,download,when} from './dom.js';
const stateLabels={completed:'回答完成',insufficient_evidence:'资料不足',error:'生成失败',failed:'生成失败',canceled:'已取消',running:'正在生成',pending:'等待生成',unconfirmed:'状态待确认'};
export function chatErrorMessage(code){return ({upstream_timeout:t('模型响应超时，请稍后重试。'),upstream_disconnected:t('模型连接中断，部分回答已保存。'),upstream_protocol_error:t('模型返回格式不兼容，请检查连接配置。'),upstream_rejected:t('模型拒绝请求，请检查连接配置与额度。'),model_not_configured:t('尚未配置可用模型，请联系组织管理员。'),output_limit:t('模型输出超过限制，部分回答已保存。'),retrieval_timeout:t('检索超时，请稍后重试。'),retrieval_unavailable:t('检索服务暂不可用，请检查资料状态。'),request_canceled:t('已停止本次回答。')})[code]||t('模型调用失败，请检查连接配置后重试。');}
export function applyChatEvent(answer,chunk){
  if(chunk.error)answer.error=typeof chunk.error==='string'?chunk.error:chunk.error.code||'upstream_error';
  const delta=chunk.choices?.[0]?.delta?.content||chunk.delta||(chunk.type==='delta'?chunk.content:'');if(typeof delta==='string')answer.content+=delta;
  if(chunk.sources)answer.sources=chunk.sources;
  const metadata=chunk.metadata||(chunk.type==='done'?chunk:null);
  if(metadata){answer.id=metadata.message_id||metadata.assistant_message_id||answer.id;answer.status=metadata.status||'completed';answer.latency_ms=metadata.latency_ms;answer.error=metadata.error||answer.error;if(metadata.answer!=null)answer.content=metadata.answer;if(metadata.content!=null)answer.content=metadata.content;if(metadata.sources)answer.sources=metadata.sources;}
  return {conversationId:metadata?.conversation_id||chunk.conversation_id,final:!!metadata&&['completed','insufficient_evidence','error','failed','canceled'].includes(answer.status)};
}
export async function render(host,{api,state,isCurrent}){
  const [kbs,history,profileData]=await Promise.all([api.request('/api/v1/knowledge-bases'),api.request('/api/v1/conversations'),api.request('/api/v1/model-profiles')]);
  const libraries=kbs.knowledge_bases||kbs.items||kbs;const profiles=profileData.model_profiles||profileData.items||profileData;
  let conversation=null,messages=[],running=null,disposed=false,selectionRevision=0;
  host.innerHTML=html`<div class="section-heading"><div><div class="eyebrow">EVIDENCE-DRIVEN ANSWERS</div><h1>回答有据，问题有解。</h1><p class="description">从选定资料生成回答，查验引用，记录需要补充的知识。</p></div><button id="newConversation" class="secondary">＋ 新对话</button></div><div class="chat-layout"><aside class="card conversation-list"><div class="card-header"><h3>会话记录</h3><button id="refreshConversations" class="quiet small">↻</button></div><div id="conversationItems"></div></aside><section class="card chat-center"><div class="chat-config"><label>模型<select id="chatModel"><option value="">部署默认模型</option>${profiles.map(profile=>`<option value="${esc(profile.id)}">${esc(profile.name)}</option>`).join('')}</select></label><details><summary>检索与生成参数</summary><div class="grid two"><label>返回片段数<input id="chatTopK" type="number" min="1" max="20" value="6"></label><label>混合权重<input id="chatAlpha" type="number" min="0" max="1" step="0.05" value="0.5"></label><label>相关性阈值<input id="chatThreshold" type="number" min="0" max="1" step="0.05" value="0"></label><label>温度<input id="chatTemperature" type="number" min="0" max="2" step="0.05" value="0.2"></label><label>最大输出 Token<input id="chatMaxTokens" type="number" min="128" max="8192" value="1024"></label><label class="inline"><input id="chatRerank" type="checkbox">启用重排</label></div><label class="inline"><input id="chatStrict" type="checkbox" checked>严格证据：资料不足时停止模型调用</label></details></div><div class="row between"><div class="knowledge-chips">${libraries.map((kb,index)=>`<label class="kb-chip"><input type="checkbox" name="chatKB" value="${esc(kb.id)}" ${index===0?'checked':''}>${esc(kb.name)}</label>`).join('')||staticHTML('<a href="#knowledge" class="hint">先建立知识库并导入资料 →</a>')}</div><button id="exportConversation" class="quiet small" disabled>导出</button></div><div id="chatMessages" class="chat-messages"></div><form id="chatForm"><textarea name="query" rows="3" required maxlength="4096" placeholder="向团队知识提问…"></textarea><div class="row between"><small class="muted">答案质量取决于资料与模型，请核查来源。</small><div class="row"><button id="stopChat" type="button" class="secondary" hidden>停止</button><button id="sendChat" type="submit" class="primary">发送问题 ↗</button></div></div></form></section><aside class="card evidence-panel"><div class="card-header"><h3>回答证据</h3><span id="sourceCount" class="badge">0</span></div><p class="card-sub">查看检索原文与引用编号。相关性分数用于排序。</p><div id="chatSources" class="empty"><strong>等待资料命中</strong>生成回答后，选择消息查看其来源。</div></aside></div>`;
  function setSources(sources=[]){$('#sourceCount',host).textContent=sources.length;$('#chatSources',host).innerHTML=sources.length?sources.map((source,index)=>html`<article class="source-card"><div class="row between"><span class="badge">[${esc(source.citation_id||index+1)}]</span><small>相关性 ${Number(source.score||0).toFixed(3)}</small></div><strong>${esc(source.filename||t('文档片段'))}</strong><p class="preserve">${esc(source.content)}</p><small class="mono">${esc(source.chunk_id||source.id||'')}</small></article>`).join(''):staticHTML('<div class="empty"><strong>未命中有效资料</strong>补充资料或检查检索范围与参数。</div>');}
  function showMessages(){const panel=$('#chatMessages',host);panel.innerHTML=messages.length?messages.map((message,index)=>`<article class="chat-message ${message.role==='user'?'user':'assistant'}"><div class="message-label"><span>${message.role==='user'?t('你'):t('知序')}</span>${message.role==='assistant'?`<span class="badge ${message.status==='completed'?'green':message.status==='insufficient_evidence'?'amber':''}">${t(stateLabels[message.status])||esc(message.status||t('回答'))}</span>`:''}</div><p class="preserve">${esc(message.content||'')}</p>${message.role==='assistant'?html`<div class="message-actions"><button class="quiet small" data-evidence="${index}">查看证据 · ${(message.sources||message.citations||[]).length}</button>${message.id&&['completed','insufficient_evidence'].includes(message.status)?html`<button class="quiet small" data-feedback="${esc(message.id)}" data-rating="positive">有帮助</button><button class="quiet small" data-feedback="${esc(message.id)}" data-rating="negative">需要改进</button>`:''}${message.latency_ms!=null?`<small>${Math.round(message.latency_ms)} ms</small>`:''}</div>`:''}</article>`).join(''):staticHTML('<div class="chat-welcome"><span>◇</span><h2>让资料回答团队的问题</h2><p>选择知识库与模型，输入一个真实业务问题。严格证据模式会在资料不足时明确说明。</p><div class="row wrap"><button class="suggested-query" data-query="产品保修期内如何申请维修？">售后政策</button><button class="suggested-query" data-query="请总结资料中的关键操作步骤，并引用来源。">操作步骤</button></div></div>');
    panel.querySelectorAll('[data-evidence]').forEach(button=>button.onclick=()=>{const message=messages[Number(button.dataset.evidence)];setSources(message.sources||message.citations||[]);});panel.querySelectorAll('[data-query]').forEach(button=>button.onclick=()=>{$('#chatForm textarea',host).value=button.dataset.query;$('#chatForm textarea',host).focus();});
    panel.querySelectorAll('[data-feedback]').forEach(button=>button.onclick=()=>showModal(button.dataset.rating==='positive'?t('记录有帮助的回答'):t('反馈需要改进的回答'),staticHTML('<label>原因（可选）<textarea name="reason" rows="3" maxlength="2000" placeholder="例如：资料缺少新产品的保修规定"></textarea></label>'),async data=>{await api.request(`/api/v1/messages/${button.dataset.feedback}/feedback`,{method:'POST',json:{rating:button.dataset.rating,reason:data.reason}});toast(t('反馈已记录，运营看板会更新知识缺口'),'success');}));panel.scrollTop=panel.scrollHeight;$('#exportConversation',host).disabled=!conversation;
  }
  async function conversationList(data=null){const result=data||await api.request('/api/v1/conversations');if(disposed)return;const items=result.conversations||result.items||result;$('#conversationItems',host).innerHTML=items.length?items.map(item=>`<button class="conversation-item ${item.id===conversation?'selected':''}" data-conversation="${esc(item.id)}"><strong>${esc(item.title||t('新对话'))}</strong><small>${when(item.updated_at||item.created_at)}</small></button>`).join(''):staticHTML('<p class="muted hint">提问后，会话将保存在当前组织。</p>');host.querySelectorAll('[data-conversation]').forEach(button=>button.onclick=async()=>{if(running)return;const revision=++selectionRevision;try{const result=await api.request(`/api/v1/conversations/${button.dataset.conversation}`);if(disposed||revision!==selectionRevision)return;conversation=button.dataset.conversation;messages=result.messages||[];showMessages();setSources(messages.findLast(item=>item.role==='assistant')?.sources||[]);await conversationList();}catch(error){toast(error.message,'error');}});}
  $('#newConversation',host).onclick=()=>{if(running)return;selectionRevision++;conversation=null;messages=[];showMessages();setSources();conversationList().catch(error=>toast(error.message,'error'));};$('#refreshConversations',host).onclick=async()=>{try{if(conversation&&!running){const revision=selectionRevision,id=conversation;const saved=await api.request(`/api/v1/conversations/${id}`);if(disposed||revision!==selectionRevision||id!==conversation)return;messages=saved.messages||[];showMessages();setSources(messages.findLast(item=>item.role==='assistant')?.sources||[]);}await conversationList();}catch(error){toast(error.message,'error');}};
  $('#exportConversation',host).onclick=async()=>{if(!conversation)return;try{const response=await api.response(`/api/v1/conversations/${conversation}/export`);download(`conversation-${conversation}.md`,await response.text(),'text/markdown');}catch(error){toast(error.message,'error');}};
  $('#chatForm',host).onsubmit=async event=>{
    event.preventDefault();if(running)return;const query=new FormData(event.target).get('query').trim();const kb_ids=Array.from(host.querySelectorAll('[name=chatKB]:checked')).map(input=>input.value);if(!query)return;if(!kb_ids.length){toast(t('请选择至少一个知识库'),'error');return;}
    const payload={query,kb_ids,conversation_id:conversation,strict_evidence:$('#chatStrict',host).checked,top_k:Number($('#chatTopK',host).value),hybrid_alpha:Number($('#chatAlpha',host).value),score_threshold:Number($('#chatThreshold',host).value),enable_reranker:$('#chatRerank',host).checked,temperature:Number($('#chatTemperature',host).value),max_tokens:Number($('#chatMaxTokens',host).value)};if($('#chatModel',host).value)payload.profile_id=$('#chatModel',host).value;
    selectionRevision++; // Invalidate detail refreshes started before this new answer.
    const priorMessageIds=new Set(messages.map(message=>message.id).filter(Boolean));
    const control=new AbortController();running=control;$('#sendChat',host).disabled=true;$('#stopChat',host).hidden=false;event.target.elements.query.value='';messages.push({role:'user',content:query});const answer={role:'assistant',content:'',status:'running',sources:[]};messages.push(answer);showMessages();let final=false;
    try{for await(const chunk of api.stream('/api/v1/chat/completions',{method:'POST',json:payload,signal:control.signal})){
      if(disposed)break;const update=applyChatEvent(answer,chunk);if(update.conversationId)conversation=update.conversationId;final=update.final||final;if(chunk.sources)setSources(answer.sources);
      showMessages();
    }if(!final&&!disposed)throw new Error(t('连接在完成确认前中断。请刷新会话查看服务器保存状态。'));if(!disposed){if(answer.status==='error'){if(!answer.content)answer.content=chatErrorMessage(answer.error);showMessages();toast(chatErrorMessage(answer.error),'error');}setSources(answer.sources);await conversationList().catch(()=>toast(t("回答状态已保存，暂时无法刷新会话列表。"),"error"));}}
    catch(error){if(!disposed){
      if(!final){
        answer.status='unconfirmed';
        if(!answer.content)answer.content=control.signal.aborted?t('停止请求已发送，等待服务器确认。'):t('连接中断，等待确认服务器保存状态。');
        showMessages();
        if(conversation)try{
          const saved=await api.request(`/api/v1/conversations/${conversation}`);
          if(!disposed){const latest=(saved.messages||[]).findLast(message=>message.role==='assistant');
            if(latest&&((answer.id&&latest.id===answer.id)||(!answer.id&&!priorMessageIds.has(latest.id)))&&['completed','insufficient_evidence','error','failed','canceled'].includes(latest.status)){
              Object.assign(answer,latest);final=true;setSources(answer.sources||[]);
            }
          }
        }catch{}
      }
      if(!disposed){showMessages();toast(final?t('连接中断，已保留服务器确认的回答状态。'):t('状态尚未确认，请刷新当前会话查看服务器保存状态。'),'error');if(conversation)await conversationList().catch(()=>{});}
    }}
    finally{running=null;if(!disposed){$('#sendChat',host).disabled=false;$('#stopChat',host).hidden=true;}}
  };$('#stopChat',host).onclick=()=>running?.abort();showMessages();await conversationList(history);
  return()=>{disposed=true;selectionRevision++;running?.abort();};
}
