import {t,html,staticHTML,localizePage,bindLanguageControl,localeURL,getLocale} from './i18n.js';
import {$,esc,toast,showModal} from './dom.js';
const base='/api/v1/model-profiles';
export async function render(host,{api,state,route}){
  const data=await api.request(base);const models=data.model_profiles||data.items||data;const admin=['owner','admin'].includes(state.workspace.role);
  host.innerHTML=html`<div class="section-heading"><div><div class="eyebrow">MODEL CONNECTIONS</div><h1>每个模型，各司其职。</h1><p class="description">为不同场景选择模型和生成参数，在工作流中并行组合或指定主模型综合。</p></div><button id="addModel" class="primary" ${admin?'':'disabled'}>＋ 添加模型连接</button></div><section class="card" style="margin-bottom:20px"><div class="row"><span class="stat-icon">◇</span><div><h3>兼容 OpenAI Chat Completions 协议</h3><p class="card-sub">可连接云端或部署者允许的本地服务。连接名称用于区分用途，支持能力以该服务实际接口为准。</p></div></div><p class="hint">API Key 使用服务器环境变量名称引用。完整凭据不会保存到组织配置、浏览器、导出文件或运行记录中。目标主机须在部署环境的允许列表中。</p></section>${models.length?`<div class="grid three">${models.map(model=>html`<section class="card model-card"><div class="card-header"><div class="row"><span class="stat-icon">◇</span><h3>${esc(model.name)}</h3></div><span class="badge">${esc(model.provider||'OpenAI compatible')}</span></div><div class="mono model-id">${esc(model.model)}</div><p class="muted ellipsis">${esc(model.base_url)}</p><div class="model-parameters"><span>温度 <strong>${esc(model.temperature)}</strong></span><span>Top P <strong>${esc(model.top_p)}</strong></span><span>Token <strong>${esc(model.max_tokens)}</strong></span><span>超时 <strong>${esc(model.timeout_seconds)}s</strong></span></div><p class="hint">凭据引用：${esc(model.api_key_env||t('无需凭据'))} · ${model.configured===false?t('未配置'):t('连接配置已保存')}</p><div class="row wrap"><button class="secondary small" data-test-model="${esc(model.id)}">测试连接</button>${admin?html`<button class="quiet small" data-edit-model="${esc(model.id)}">配置参数</button><button class="quiet small" data-delete-model="${esc(model.id)}">删除</button>`:''}</div><div class="hint" data-model-result="${esc(model.id)}"></div></section>`).join('')}</div>`:staticHTML('<div class="empty card"><strong>连接第一个模型</strong>添加模型后，即可在问答和可视化工作流中使用。</div>')}`;
  function edit(model={}){showModal(model.id?t('配置模型连接'):t('添加模型连接'),html`<div class="grid two"><label>连接名称<input name="name" required maxlength="128" value="${esc(model.name||'')}" placeholder="例如：客服主模型"></label><label>调用协议<select name="provider"><option value="openai-compatible">OpenAI Chat Completions 兼容协议</option></select></label></div><label>兼容 API 地址<input name="base_url" type="url" required value="${esc(model.base_url||'https://api.openai.com/v1')}" placeholder="https://provider.example/v1"></label><div class="grid two"><label>模型 ID<input name="model" required maxlength="200" value="${esc(model.model||'')}" placeholder="填写服务实际模型 ID"></label><label>凭据环境变量名称<input name="api_key_env" pattern="[A-Za-z_][A-Za-z0-9_]*" maxlength="100" value="${esc(model.api_key_env||'')}" placeholder="例如：SUPPORT_MODEL_API_KEY"></label></div><div class="grid two"><label>温度<input name="temperature" type="number" min="0" max="2" step="any" value="${model.temperature??0.2}" required></label><label>Top P<input name="top_p" type="number" min="0.000001" max="1" step="any" value="${model.top_p??1}" required></label><label>最大输出 Token<input name="max_tokens" type="number" min="1" max="8192" value="${model.max_tokens??1024}" required></label><label>请求超时（秒）<input name="timeout_seconds" type="number" min="0.05" max="120" step="any" value="${model.timeout_seconds??60}" required></label></div><label>系统提示<textarea name="system_prompt" rows="4" maxlength="8000">${esc(model.system_prompt||'根据资料回答，给出来源编号。')}</textarea></label><p class="hint">自建无鉴权服务可留空凭据引用。服务器只解析部署者明确允许的环境变量引用。连接测试会发送合成的简短请求。</p>`,async data=>{for(const key of ['temperature','top_p','max_tokens','timeout_seconds'])data[key]=Number(data[key]);data.api_key_env=data.api_key_env||null;await api.request(model.id?`${base}/${model.id}`:base,{method:model.id?'PATCH':'POST',json:data});await route();toast(t('模型连接已保存'),'success');});}
  $('#addModel',host).onclick=()=>edit();host.querySelectorAll('[data-edit-model]').forEach(button=>button.onclick=()=>edit(models.find(model=>model.id===button.dataset.editModel)));
  host.querySelectorAll('[data-delete-model]').forEach(button=>button.onclick=async()=>{if(!confirm(t('删除此模型连接？引用它的工作流需要重新配置。')))return;try{await api.request(`${base}/${button.dataset.deleteModel}`,{method:'DELETE'});await route();}catch(error){toast(error.message,'error');}});
  host.querySelectorAll('[data-test-model]').forEach(button=>{button.disabled=!admin;button.onclick=async()=>{button.disabled=true;const output=host.querySelector(`[data-model-result="${button.dataset.testModel}"]`);output.textContent=t('正在测试连接…');try{const result=await api.request(`${base}/${button.dataset.testModel}/test`,{method:'POST',json:{}});output.textContent=`${result.ok?t('连接成功'):t('连接失败')} · ${result.latency_ms??'—'} ms${result.error?` · ${result.error}`:''}`;}catch(error){output.textContent=error.message;}finally{button.disabled=false;}};});
}
