import {$,esc,toast,showModal,when,download} from './dom.js';

const heading=(label,title,subtitle,actions='')=>`<div class="section-heading"><div><div class="eyebrow">${label}</div><h1>${title}</h1><p class="description">${subtitle}</p></div><div class="toolbar">${actions}</div></div>`;
const empty=(title,detail)=>`<div class="empty"><strong>${title}</strong>${detail}</div>`;
const roleName={owner:'所有者',admin:'管理员',editor:'知识编辑',viewer:'只读成员'};

export async function render(host,ctx){return ({overview,team,billing,settings}[ctx.state.view])(host,ctx);}

async function overview(host,{api,state}) {
  const data=await api.request('/api/v1/insights');
  const counts=data.documents||data.counts||{};const answers=data.answers||{};const gaps=data.gaps||[];
  const stats=[['就绪文档',counts.completed??counts.documents_completed??0,'可用于检索与问答','▤'],['完成回答',answers.completed??0,'基于服务端已完成记录','◇'],['资料不足',answers.insufficient_evidence??0,'优先补充这些问题的知识','◎'],['平均响应',data.latency_ms?.average!=null?`${Math.round(data.latency_ms.average)} ms`:'—','没有完成记录时不显示估计','↗']];
  host.innerHTML=heading('WORKSPACE OVERVIEW','知识有序，服务有据。',`${esc(state.workspace.name)} · 掌握知识资产、回答效果与需要补充的资料。`,'<a href="#knowledge" class="secondary">导入文档</a><a href="#chat" class="primary">开始问答 →</a>')+`<section class="hero"><span class="badge green">CONNECTED KNOWLEDGE</span><h2>把团队资料连接成<br>可验证的服务能力。</h2><p>选择知识库，配置检索与模型，把回答依据留在每一次对话中。通过负反馈与资料缺口，持续维护团队知识。</p><div class="row wrap"><a href="#workflows" class="primary">打开可视化编排 ↗</a><a href="#evaluation" class="quiet">测试检索效果</a></div></section><div class="grid four" style="margin-bottom:22px">${stats.map(([name,value,detail,icon])=>`<article class="card stat"><div class="stat-top"><span>${name}</span><span class="stat-icon">${icon}</span></div><strong>${esc(value)}</strong><small>${detail}</small></article>`).join('')}</div><div class="grid two"><section class="card"><div class="card-header"><h2>知识缺口</h2><span class="badge amber">${gaps.length} 个待关注问题</span></div><p class="card-sub">来自资料不足的提问与明确的负反馈。</p>${gaps.length?gaps.slice(0,8).map(item=>`<div class="activity-item"><span class="activity-dot"></span><div><strong>${esc(item.query)}</strong><p>${esc(item.count||1)} 次 · ${esc(item.reason||'资料不足')} · ${when(item.last_seen||item.created_at)}</p></div></div>`).join(''):empty('暂无知识缺口','开始问答后，这里会记录值得补充和改进的内容。')}</section><section class="card"><div class="card-header"><h2>连接你的知识工作流</h2><span class="badge">GET STARTED</span></div><div class="stack"><a class="step-card" href="#knowledge"><span class="step-number">01</span><div><strong>建立知识库</strong><p>上传手册、规范与客服资料</p></div></a><a class="step-card" href="#models"><span class="step-number">02</span><div><strong>连接模型</strong><p>配置模型、参数与安全凭据引用</p></div></a><a class="step-card" href="#workflows"><span class="step-number">03</span><div><strong>组合检索与生成模块</strong><p>拖拽节点、试运行、发布版本</p></div></a><a class="step-card" href="#evaluation"><span class="step-number">04</span><div><strong>验证效果并持续维护</strong><p>检查来源、测量召回、处理知识缺口</p></div></a></div></section></div>`;
}

async function team(host,ctx) {
  const {api,state,route,refreshIdentity}=ctx;const base=`/api/v1/organizations/${state.workspace.id}`;const admin=['owner','admin'].includes(state.workspace.role);
  const [members,invites,keys]=await Promise.all([api.request(`${base}/members`),admin?api.request(`${base}/invitations`):{invitations:[]},admin?api.request('/api/v1/api-keys'):{api_keys:[]}]);
  host.innerHTML=heading('TEAM & ACCESS','团队与权限','以组织角色管理知识维护、模型配置与访问范围。',`${admin?'<button id="inviteMember" class="primary">＋ 邀请成员</button>':''}<button id="acceptInvite" class="secondary">接受邀请</button>`)+`<section class="card"><div class="card-header"><h2>组织成员</h2><span class="badge">${members.members.length} 位成员</span></div><div class="table-wrap"><table><thead><tr><th>成员</th><th>角色</th><th>加入时间</th><th></th></tr></thead><tbody>${members.members.map(member=>`<tr><td><div class="filename"><span class="avatar">${esc(member.email[0].toUpperCase())}</span><div>${esc(member.name||member.email)}<br><small>${esc(member.email)}</small></div></div></td><td>${admin?`<select data-role="${esc(member.user_id)}" aria-label="${esc(member.email)} 的角色">${Object.entries(roleName).map(([id,name])=>`<option value="${id}" ${id===member.role?'selected':''}>${name}</option>`).join('')}</select>`:roleName[member.role]}</td><td class="muted">${when(member.created_at)}</td><td>${admin?`<button class="quiet small" data-remove="${esc(member.user_id)}">移除</button>`:''}</td></tr>`).join('')}</tbody></table></div></section>${admin?`<div class="grid two" style="margin-top:22px"><section class="card"><div class="card-header"><h2>邀请记录</h2></div>${invites.invitations.length?invites.invitations.map(invite=>`<div class="activity-item"><span class="activity-dot"></span><div style="flex:1"><strong>${esc(invite.email)}</strong><p>${roleName[invite.role]} · ${invite.accepted_at?'已接受':invite.revoked_at?'已撤销':`有效至 ${when(invite.expires_at)}`}</p></div>${!invite.accepted_at&&!invite.revoked_at?`<button class="quiet small" data-revoke-invite="${invite.id}">撤销</button>`:''}</div>`).join(''):empty('还没有邀请','创建邀请后，复制一次性邀请令牌给团队成员。')}</section><section class="card"><div class="card-header"><h2>API 访问密钥</h2><button id="createKey" class="secondary small">＋ 创建</button></div><p class="card-sub">密钥绑定创建者与当前组织，完整值只在创建时显示。</p>${keys.api_keys.length?keys.api_keys.map(key=>`<div class="activity-item"><span class="activity-dot"></span><div style="flex:1"><strong>${esc(key.name)}</strong><p class="mono">${esc(key.prefix)}… · ${key.revoked_at?'已撤销':`到期 ${when(key.expires_at)}`}</p></div>${!key.revoked_at?`<button data-revoke-key="${key.id}" class="quiet small">撤销</button>`:''}</div>`).join(''):empty('尚未创建访问密钥','可用于客服系统或你自己的 Agent 集成。')}</section></div>`:''}`;
  const secretDialog=(title,value)=>showModal(title,`<p class="muted">请现在复制并妥善保存。关闭后无法再次查看完整值。</p><textarea readonly rows="4">${esc(value)}</textarea>`,async()=>{});
  $('#inviteMember',host)?.addEventListener('click',()=>showModal('邀请团队成员',`<label>邮箱<input name="email" type="email" required></label><label>角色<select name="role">${Object.entries(roleName).filter(([role])=>role!=='owner'||state.workspace.role==='owner').map(([role,name])=>`<option value="${role}" ${role==='viewer'?'selected':''}>${name}</option>`).join('')}</select></label>`,async data=>{const result=await api.request(`${base}/invitations`,{method:'POST',json:data});await route();setTimeout(()=>secretDialog('邀请链接与令牌',`${location.origin}/#team?invite=${encodeURIComponent(result.token)}\n\n${result.token}`),0);}));
  const acceptDialog=(token='')=>showModal('接受团队邀请',`<label>邀请令牌<textarea name="token" rows="3" required minlength="32" maxlength="128">${esc(token)}</textarea></label><p class="muted">登录邮箱必须与邀请目标邮箱一致。</p>`,async data=>{const result=await api.request('/api/v1/invitations/accept',{method:'POST',json:{token:data.token.trim()}});await refreshIdentity(result.organization.id);if(location.hash.includes('?'))history.replaceState(null,'','#team');await route();toast('已加入团队','success');});
  $('#acceptInvite',host).onclick=()=>acceptDialog();
  const pendingToken=new URLSearchParams(location.hash.split('?')[1]||'').get('invite');
  if(pendingToken&&pendingToken.length<=128)setTimeout(()=>{if(ctx.isCurrent())acceptDialog(pendingToken);},0);
  $('#createKey',host)?.addEventListener('click',()=>showModal('创建 API 密钥','<label>名称<input name="name" required maxlength="128" placeholder="例如：客服系统集成"></label>',async data=>{const result=await api.request('/api/v1/api-keys',{method:'POST',json:data});await route();setTimeout(()=>secretDialog('新的 API 密钥',result.key),0);}));
  host.querySelectorAll('[data-role]').forEach(select=>select.onchange=async()=>{try{await api.request(`${base}/members/${select.dataset.role}`,{method:'PATCH',json:{role:select.value}});await refreshIdentity();await route();toast('角色已更新','success');}catch(error){toast(error.message,'error');await route();}});
  const bindRemove=(selector,path,question)=>host.querySelectorAll(selector).forEach(button=>button.onclick=async()=>{if(!confirm(question))return;try{await api.request(path(button),{method:'DELETE'});await route();}catch(error){toast(error.message,'error');}});
  bindRemove('[data-remove]',button=>`${base}/members/${button.dataset.remove}`,'确定移除此成员并撤销其组织访问密钥？');
  bindRemove('[data-revoke-invite]',button=>`${base}/invitations/${button.dataset.revokeInvite}`,'确定撤销邀请？');
  bindRemove('[data-revoke-key]',button=>`/api/v1/api-keys/${button.dataset.revokeKey}`,'确定撤销此密钥？');
}

async function billing(host,{api,state}) {
  const [plans,result]=await Promise.all([api.request('/api/v1/billing/plans'),api.request('/api/v1/billing/subscription')]);
  const entries=Array.isArray(plans)?plans:plans.plans||[];const admin=['owner','admin'].includes(state.workspace.role);
  result.usage={...result.usage,monthly_answers:(result.usage?.completed_answers||0)+(result.usage?.reserved_answers||0)};
  host.innerHTML=heading('SUBSCRIPTION & USAGE','订阅与用量','查看当前权益和实际使用量，按团队需要调整订阅。',admin?'<button id="billingPortal" class="secondary">管理订阅 ↗</button>':'')+`<section class="card" style="margin-bottom:22px"><div class="card-header"><div><h2>当前套餐：${esc(result.plan||'free').toUpperCase()}</h2><p class="card-sub">订阅状态：${esc(result.status||'free')} · 权益由服务端订阅状态决定</p></div><span class="badge green">${esc(result.plan||'free').toUpperCase()}</span></div><div class="grid four">${Object.entries(result.limits||{}).map(([name,limit])=>`<div><small>${({members:'团队成员',knowledge_bases:'知识库',documents:'文档',monthly_answers:'每月问答',answers:'每月问答'})[name]||esc(name)}</small><div style="margin-top:10px;font-size:20px">${esc(typeof result.usage?.[name]==='number'?result.usage[name]:'—')} <small>/ ${esc(limit)}</small></div></div>`).join('')}</div></section><div class="grid three">${entries.map(plan=>`<section class="card plan-card ${plan.id==='team'||plan.plan==='team'?'recommended':''}"><div class="row between"><h3>${esc(plan.name||plan.id||plan.plan)}</h3>${plan.id==='team'||plan.plan==='team'?'<span class="badge green">TEAM</span>':''}</div><div class="price">${plan.id==='free'||plan.plan==='free'?'免费':'部署者配置价格'}</div><p class="card-sub">${esc(plan.description||'按组织提供额度与协作能力')}</p><ul>${Object.entries(plan.limits||{}).map(([name,count])=>`<li>${esc(count)} ${({members:'位成员',knowledge_bases:'个知识库',documents:'份文档',monthly_answers:'次问答 / 月',answers:'次问答 / 月'})[name]||esc(name)}</li>`).join('')}</ul>${admin&&['team','business'].includes(plan.id||plan.plan)?`<button class="${plan.id==='team'||plan.plan==='team'?'primary':'secondary'}" data-upgrade="${esc(plan.id||plan.plan)}">选择此套餐 →</button>`:'<span class="badge">基础工作空间</span>'}</section>`).join('')}</div><p class="hint" style="margin-top:22px">付费连接需要部署者配置 Stripe。未配置时不会创建付款或假定订阅生效；页面跳转成功后仍以服务器收到的有效订阅事件为准。</p>`;
  $('#billingPortal',host)?.addEventListener('click',async()=>{try{const data=await api.request('/api/v1/billing/portal',{method:'POST',json:{}});safePaymentRedirect(data.url);}catch(error){toast(error.message,'error');}});
  host.querySelectorAll('[data-upgrade]').forEach(button=>button.onclick=async()=>{button.disabled=true;try{const data=await api.request('/api/v1/billing/checkout',{method:'POST',json:{plan:button.dataset.upgrade}});safePaymentRedirect(data.url);}catch(error){toast(error.message,'error');}finally{button.disabled=false;}});
}
function safePaymentRedirect(value){const url=new URL(value);if(url.protocol!=='https:'||!['checkout.stripe.com','billing.stripe.com'].includes(url.hostname))throw new Error('付款服务返回了不支持的地址');location.assign(url.href);}

async function settings(host,{api,state,refreshIdentity,route}) {
  const admin=['owner','admin'].includes(state.workspace.role);const workspace=await api.request(`/api/v1/organizations/${state.workspace.id}`);
  host.innerHTML=heading('WORKSPACE SETTINGS','工作空间设置','组织资料与部署配置分开管理。')+`<section class="card" style="max-width:760px"><h2>组织资料</h2><form id="workspaceForm" class="stack"><label>名称<input name="name" value="${esc(workspace.name)}" maxlength="128" required ${admin?'':'disabled'}></label><label>描述<textarea name="description" rows="3" maxlength="512" ${admin?'':'disabled'}>${esc(workspace.description||'')}</textarea></label>${admin?'<div><button class="primary" type="submit">保存资料</button></div>':''}</form></section><section class="card" style="margin-top:22px;max-width:760px"><h2>部署连接</h2><p class="muted">数据库、文件存储、向量索引、允许的模型主机和支付凭据由部署环境配置。组织模型参数可在“模型连接”中管理，知识库入库参数可在知识库详情中调整。</p><div class="row wrap"><a href="#models" class="secondary">模型连接</a><a href="#knowledge" class="quiet">知识库参数</a><a href="/docs" class="quiet" target="_blank" rel="noopener">API 文档 ↗</a></div></section>`;
  $('#workspaceForm',host).onsubmit=async event=>{event.preventDefault();try{const data=Object.fromEntries(new FormData(event.target));await api.request(`/api/v1/organizations/${state.workspace.id}`,{method:'PATCH',json:data});await refreshIdentity();await route();toast('工作空间资料已保存','success');}catch(error){toast(error.message,'error');}};
}
