import {t,html,staticHTML,localizePage,bindLanguageControl,localeURL,getLocale} from './i18n.js';
import {$,esc,toast,showModal,download,when} from './dom.js';
import {NODE_TYPES,template,validateGraph} from './graph.js';
import {GraphCanvas} from './canvas.js';
import {runWorkflow} from './workflow-run.js';
import {mergeFileOptions} from './file-selection.js';

const runLabels={pending:'等待执行',queued:'等待运行',running:'正在运行',canceling:'正在取消',completed:'运行完成',degraded:'部分分支失败',insufficient_evidence:'资料不足',error:'运行失败',canceled:'已取消',timed_out:'运行超时',skipped:'已跳过'};

const base='/api/v1/workflows';
export async function render(host,{api,state,isCurrent}){
  const [items,kbs,profiles]=await Promise.all([api.request(base),api.request('/api/v1/knowledge-bases'),api.request('/api/v1/model-profiles')]);
  const libraries=kbs.knowledge_bases||kbs.items||kbs;const models=profiles.model_profiles||profiles.items||profiles;
  const editable=['owner','admin','editor'].includes(state.workspace.role);let current=null,dirty=false,running=null,disposed=false,selectionRevision=0,saving=null;
  host.innerHTML=html`<div class="section-heading"><div><div class="eyebrow">VISUAL KNOWLEDGE ORCHESTRATION</div><h1>组合知识，编排答案。</h1><p class="description">连接检索与模型模块，试运行检查每一步，再发布供团队使用。</p></div><div class="toolbar"><button id="newWorkflow" class="primary" ${editable?'':'disabled'}>＋ 新建工作流</button></div></div><div class="workflow-toolbar card"><select id="workflowSelect" aria-label="工作流"><option value="">未保存的工作流</option>${(items.workflows||items).map(item=>`<option value="${esc(item.id)}">${esc(item.name)}</option>`).join('')}</select><input id="workflowName" value="严格客服工作流" aria-label="工作流名称" maxlength="128"><span id="draftState" class="badge amber">未保存</span><div class="grow"></div><button id="undoGraph" class="quiet" title="撤销">↶</button><button id="redoGraph" class="quiet" title="重做">↷</button><button id="validateGraph" class="secondary">校验</button><button id="saveGraph" class="secondary" ${editable?'':'disabled'}>保存草稿</button><button id="publishGraph" class="primary" ${editable?'':'disabled'}>发布版本 ↗</button></div><div class="workflow-layout"><aside class="node-library card"><div class="eyebrow">模块库</div><h3>拖入画布</h3>${Object.entries(NODE_TYPES).map(([type,meta])=>`<button class="library-node" draggable="${editable}" data-type="${type}" ${editable?'':'disabled'}><span>${meta.icon}</span>${t(meta.name)}<small>＋</small></button>`).join('')}<div class="divider"></div><label>快速模板<select id="graphTemplate"><option value="strict">严格证据客服</option><option value="multi-kb">多知识库汇总</option><option value="multi-model">多模型并行融合</option></select></label><div class="row"><button id="exportGraph" class="quiet small">导出 JSON</button><button id="importGraph" class="quiet small" ${editable?'':'disabled'}>导入</button></div></aside><section id="graphCanvas" class="graph-canvas" aria-label="可视化工作流画布"></section><aside id="nodeSettings" class="card node-settings"><div class="eyebrow">节点参数</div><h3>选择一个模块</h3><p class="muted">配置知识库范围、检索参数、模型连接与生成策略。</p><p class="hint">输出端口与输入端口可拖动连线，也可依次点击连接。编辑参数后点击“应用参数”。</p></aside></div><div class="grid two" style="margin-top:18px"><section class="card"><div class="card-header"><h2>试运行与追踪</h2><span id="runStatus" class="badge">READY</span></div><form id="runForm" class="stack"><label>测试问题<textarea name="query" rows="2" required maxlength="8000" placeholder="例如：保修期内的产品如何申请售后？"></textarea></label><div class="row wrap"><label class="inline"><input id="publishedRun" type="checkbox">使用已发布版本</label><div class="grow"></div><button id="cancelRun" type="button" class="quiet" hidden>取消</button><button class="primary" id="runButton" type="submit">▶ 试运行</button></div></form><div id="runResult"></div></section><section class="card"><div class="card-header"><h2>版本与运行记录</h2><button id="refreshHistory" class="quiet small">刷新</button></div><div id="workflowHistory" class="muted">保存后可查看不可变发布版本与运行记录。</div></section></div>`;
  const canvas=new GraphCanvas($('#graphCanvas',host),template(),{editable,onSelect:node=>settings(node),onChange:()=>{dirty=true;$('#draftState',host).textContent=t('草稿有修改');}});
  requestAnimationFrame(()=>{if(!disposed)canvas.fit();});
  function settings(node){const panel=$('#nodeSettings',host);if(!node){panel.innerHTML=staticHTML('<div class="eyebrow">节点参数</div><h3>选择一个模块</h3><p class="muted">选择模块后设置检索和生成参数。</p>');return;}const input=(key,label,min,max,step=1)=>`<label>${label}<input name="${key}" type="number" min="${min}" max="${max}" step="${step}" value="${esc(node.config[key]??NODE_TYPES[node.type].defaults[key]??'')}" required></label>`;const modelSelect=()=>html`<label>模型连接<select name="profile_id"><option value="">选择模型连接</option>${models.map(model=>`<option value="${esc(model.id)}" ${model.id===node.config.profile_id?'selected':''}>${esc(model.name)} · ${esc(model.model||model.model_id)}</option>`).join('')}</select></label>`;let fields='';
    if(node.type==='retrieval')fields=html`<label>知识库选择<select name="kb_ids" multiple size="${Math.min(5,Math.max(2,libraries.length))}">${libraries.map(kb=>`<option value="${esc(kb.id)}" ${(node.config.kb_ids||[]).includes(kb.id)?'selected':''}>${esc(kb.name)}</option>`).join('')}</select></label><p class="hint">按 Ctrl / Command 多选。仅当前组织知识库可用。</p>${input('top_k',t('返回片段数'),1,50)}${input('hybrid_alpha',t('向量 / 关键词混合权重'),0,1,0.05)}${input('score_threshold',t('相关性阈值'),0,1,0.05)}${input('context_chars',t('上下文字符预算'),1000,50000,100)}<label class="inline"><input name="enable_reranker" type="checkbox" ${node.config.enable_reranker?'checked':''}>启用重排</label>`;
    if(node.type==='files')fields=html`<label>知识库选择<select name="kb_ids" multiple size="3">${libraries.map(kb=>`<option value="${esc(kb.id)}" ${(node.config.kb_ids||[]).includes(kb.id)?'selected':''}>${esc(kb.name)}</option>`).join('')}</select></label><label>已解析文件<select name="doc_ids" multiple size="6"></select></label><button id="moreFiles" type="button" class="quiet small">加载更多文件</button><p class="hint">读取选中文档的已入库片段，按文件顺序取证。解析模块在知识库参数中配置；需要语义匹配时连接检索模块。</p>${input('top_k',t('返回片段数'),1,50)}${input('context_chars',t('上下文字符预算'),1000,50000,100)}`;
    if(node.type==='filter')fields=html`<label>元数据匹配（JSON 对象）<textarea name="metadata" rows="5">${esc(JSON.stringify(node.config.metadata||{},null,2))}</textarea></label><p class="hint">仅支持 SQL 片段元数据 kb_id（知识库 UUID）与 chunk_index（整数序号）；其他字段不会匹配。</p>`;
    if(node.type==='deduplicate')fields=input('top_k',t('保留片段数'),1,50)+input('context_chars',t('上下文字符预算'),1000,50000,100);
    if(node.type==='rerank')fields=input('top_k',t('重排后保留数'),1,50);
    if(node.type==='evidence')fields=input('min_sources',t('最少证据片段'),1,50)+staticHTML('<p class="hint">证据不足时停止后续模型调用，并明确返回资料不足。</p>');
    if(node.type==='prompt')fields=html`<label>系统提示<textarea name="system_prompt" rows="8" maxlength="8000">${esc(node.config.system_prompt||'')}</textarea></label><p class="hint">平台仍会附加资料不可信与引用约束。</p>`;
    if(node.type==='model')fields=modelSelect()+input('temperature',t('温度'),0,2,0.05)+input('top_p','Top P',0.000001,1,'any')+input('max_tokens',t('最大输出 Token'),1,8192)+input('timeout_seconds',t('调用超时（秒）'),0.05,120,'any');
    if(node.type==='merge')fields=html`<label>融合方式<select name="mode"><option value="concatenate" ${node.config.mode==='concatenate'?'selected':''}>并列展示</option><option value="synthesize" ${node.config.mode==='synthesize'?'selected':''}>主模型综合</option></select></label>${modelSelect()}${input('temperature',t('综合温度'),0,2,0.05)}${input('max_tokens',t('最大输出 Token'),1,8192)}<p class="hint">主模型综合会增加一次模型调用；模型意见一致不能代替事实核查。</p>`;
    panel.innerHTML=html`<div class="eyebrow">${esc(node.type.toUpperCase())}</div><h3>${esc(t(NODE_TYPES[node.type].name))}</h3><form id="nodeForm" class="stack"><label>模块名称<input name="label" value="${esc(node.label)}" maxlength="80" required></label>${fields}<div class="row"><button class="primary small" type="submit" ${editable?'':'disabled'}>应用参数</button><button id="removeNode" class="quiet small" type="button" ${editable?'':'disabled'}>删除模块</button></div></form>`;
    if(node.type==='files'){
      const form=$('#nodeForm',panel),select=form.elements.doc_ids;let loadRevision=0,page=1,loaded=[];
      function drawFiles(){select.innerHTML=loaded.map(doc=>`<option value="${esc(doc.id)}" ${doc.selected?'selected':''}>${esc(doc.filename)}</option>`).join('');}
      loaded=mergeFileOptions([],[],node.config.doc_ids);drawFiles();
      async function loadFiles(reset=false){
        if(reset){page=1;loaded=[];}const revision=++loadRevision;
        if(reset)drawFiles();
        const ids=Array.from(form.elements.kb_ids.selectedOptions).map(option=>option.value);
        if(ids.length>20)throw new Error(t('最多选择 20 个知识库'));
        const lists=await Promise.all(ids.map(id=>api.request(`/api/v1/kb/${id}/documents?page=${page}&page_size=100`)));
        if(disposed||revision!==loadRevision||!panel.contains(form))return;
        const ready=lists.flatMap(list=>(list.items||[]).filter(doc=>doc.status==='completed'));
        const selectedIds=Array.from(select.selectedOptions).map(option=>option.value);
        loaded=mergeFileOptions(loaded,ready,selectedIds);drawFiles();
        $('#moreFiles',panel).disabled=lists.every(list=>page*100>=list.total);
      }
      form.elements.kb_ids.onchange=()=>loadFiles(true).catch(error=>toast(error.message,'error'));
      $('#moreFiles',panel).onclick=()=>{page++;loadFiles().catch(error=>toast(error.message,'error'));};
      loadFiles().catch(error=>toast(error.message,'error'));
    }
    $('#nodeForm',panel).onsubmit=event=>{event.preventDefault();try{const form=event.target;const data=Object.fromEntries(new FormData(form)),config={...node.config};for(const [key,value] of Object.entries(data)){if(key==='label')continue;config[key]=key==='metadata'?JSON.parse(value):form.elements[key]?.type==='number'?Number(value):value;}if(['retrieval','files'].includes(node.type)){config.kb_ids=Array.from(form.elements.kb_ids.selectedOptions).map(option=>option.value);if(node.type==='retrieval')config.enable_reranker=form.elements.enable_reranker.checked;else config.doc_ids=Array.from(form.elements.doc_ids.selectedOptions).map(option=>option.value);}if(config.metadata&&(!Object.prototype.toString.call(config.metadata).includes('Object')||Array.isArray(config.metadata)))throw new Error(t('元数据需要 JSON 对象'));canvas.update(node.id,{label:data.label,config});toast(t('参数已应用到草稿'),'success');}catch(error){toast(error.message,'error');}};$('#removeNode',panel).onclick=()=>canvas.remove();
  }
  async function history(){if(!current)return;const id=current.id,revision=selectionRevision;const [versions,runs]=await Promise.all([api.request(`${base}/${current.id}/versions`),api.request(`${base}/${current.id}/runs`)]);if(disposed||current?.id!==id||revision!==selectionRevision)return;$('#workflowHistory',host).innerHTML=html`<h3>发布版本</h3>${(versions.versions||versions).map(version=>html`<div class="activity-item"><span class="activity-dot"></span><div class="grow"><strong>版本 ${esc(version.version||version.number)}</strong><p>${when(version.created_at)}${(version.id===current.published_version_id)?t(' · 当前发布'):''}</p></div>${editable?html`<button class="quiet small" data-rollback="${esc(version.id)}">回滚到此版</button>`:''}</div>`).join('')||staticHTML('<p class="muted">尚未发布</p>')}<div class="divider"></div><h3>最近运行</h3>${(runs.runs||runs).slice(0,8).map(run=>`<button class="run-row" data-run="${esc(run.id)}"><span class="badge ${run.status==='completed'?'green':'amber'}">${esc(t(runLabels[run.status])||run.status)}</span><span>${when(run.created_at)}</span><small>${esc(run.duration_ms??'—')} ms →</small></button>`).join('')||staticHTML('<p class="muted">尚无运行</p>')}`;host.querySelectorAll('[data-rollback]').forEach(button=>button.onclick=async()=>{try{current=await api.request(`${base}/${current.id}/rollback`,{method:'POST',json:{version_id:button.dataset.rollback}});toast(t('已切换发布版本'),'success');await history();}catch(error){toast(error.message,'error');}});host.querySelectorAll('[data-run]').forEach(button=>button.onclick=async()=>{try{showRun(await api.request(`${base}/${current.id}/runs/${button.dataset.run}`));}catch(error){toast(error.message,'error');}});}
  async function save(){
    if(!editable)throw new Error(t('需要知识编辑权限'));
    if(saving)return saving;
    const revision=selectionRevision,id=current?.id,graph=canvas.get();
    const payload={name:$('#workflowName',host).value.trim(),graph};
    if(!payload.name)throw new Error(t('请填写工作流名称'));
    saving=(async()=>{
      const saved=await api.request(id?`${base}/${id}`:base,{method:id?'PATCH':'POST',json:payload});
      if(disposed||revision!==selectionRevision)throw new Error(t('工作流已切换；先前草稿已保存'));
      current=saved;
      dirty=JSON.stringify(canvas.get())!==JSON.stringify(graph)||$('#workflowName',host).value.trim()!==payload.name;
      $('#draftState',host).textContent=dirty?t('草稿有修改'):t('草稿已保存');
      const select=$('#workflowSelect',host);
      if(!Array.from(select.options).some(option=>option.value===current.id)){
        const option=document.createElement('option');option.value=current.id;option.textContent=current.name;select.append(option);
      }
      select.value=current.id;await history();return current;
    })();
    try{return await saving;}finally{saving=null;}
  }
  function showRun(run){const sources=run.sources||[];$('#runStatus',host).textContent=t(runLabels[run.status])||run.status;$('#runResult',host).innerHTML=`${run.status==='degraded'?staticHTML('<p class="hint">部分模型分支失败，当前展示成功分支的结果。请查看追踪记录与回答证据。</p>'):''}<div class="run-answer"><strong>${run.status==='insufficient_evidence'?t('资料不足'):['completed','degraded'].includes(run.status)?t('运行回答'):t('运行状态')}</strong><p class="preserve">${esc(run.status==='insufficient_evidence'?t('所选知识库没有足够资料回答此问题，请补充资料或调整检索范围。'):run.answer||run.content||t(runLabels[run.status])||'')}</p>${run.error?`<small class="muted">${esc(run.error)}</small>`:''}</div>${sources.length?html`<details class="result-details"><summary>查看回答证据 · ${sources.length} 个片段</summary>${sources.map((source,index)=>`<article class="source-card"><strong>[${index+1}] ${esc(source.filename||t('文档片段'))}</strong><p class="preserve">${esc(source.content)}</p><small class="mono">${esc(source.chunk_id||'')}</small></article>`).join('')}</details>`:''}<div class="trace-list">${(run.trace||run.traces||[]).map(step=>html`<div class="trace-step"><span class="activity-dot"></span><div class="grow"><strong>${esc(step.label||step.node_id)}</strong><small>${esc(t(runLabels[step.status])||step.status)} · ${esc(step.result_count??step.count??0)} 条结果${step.error?` · ${esc(step.error)}`:''}</small>${step.config_refs&&Object.keys(step.config_refs).length?html`<details><summary>本次参数</summary><p class="mono preserve">${esc(JSON.stringify(step.config_refs,null,2))}</p></details>`:''}</div><span class="mono">${esc(step.duration_ms??0)} ms</span></div>`).join('')}</div>`;}
  const action=(id,fn)=>$(id,host).onclick=async()=>{try{await fn();}catch(error){toast(error.message,'error');}};
  action('#newWorkflow',()=>{if(dirty&&!confirm(t('放弃未保存的草稿？')))return;selectionRevision++;current=null;canvas.set(template());$('#workflowName',host).value=t('新工作流');$('#workflowSelect',host).value='';$('#workflowHistory',host).textContent=t('保存后可查看版本与运行记录。');});
  action('#saveGraph',async()=>{await save();toast(t('草稿已保存'),'success');});action('#publishGraph',async()=>{const errors=validateGraph(canvas.get());if(errors.length)throw new Error(errors.join('；'));await save();if(dirty)throw new Error(t('草稿在保存期间有修改，请再次保存后发布'));current=await api.request(`${base}/${current.id}/publish`,{method:'POST',json:{}});$('#draftState',host).textContent=t('已发布');await history();toast(t('版本已发布'),'success');});
  action('#validateGraph',async()=>{const errors=validateGraph(canvas.get());if(errors.length)throw new Error(errors.join('；'));await api.request(`${base}/validate`,{method:'POST',json:{graph:canvas.get()}});toast(t('结构、资源与参数校验通过'),'success');});
  action('#undoGraph',()=>canvas.undo());action('#redoGraph',()=>canvas.redo());action('#refreshHistory',()=>history());action('#exportGraph',()=>download(`${$('#workflowName',host).value||'workflow'}.json`,{schema_version:1,name:$('#workflowName',host).value,graph:canvas.get()}));
  action('#importGraph',()=>showModal(t('导入工作流'),staticHTML('<label>工作流 JSON<textarea name="json" rows="12" required maxlength="100000"></textarea></label><p class="muted">模型与知识库 ID 需要在当前组织存在；导入后仍须服务端校验。</p>'),async data=>{const value=JSON.parse(data.json);const graph=value.graph||value;const errors=validateGraph(graph,{complete:false});if(errors.length)throw new Error(errors.join('；'));canvas.set(graph);if(value.name)$('#workflowName',host).value=String(value.name).slice(0,128);}));
  $('#graphTemplate',host).onchange=event=>{if(dirty&&!confirm(t('用模板替换当前草稿？')))return;canvas.set(template(event.target.value));};
  $('#workflowName',host).oninput=()=>{dirty=true;$('#draftState',host).textContent=t('草稿有修改');};
  $('#workflowSelect',host).onchange=async event=>{if(dirty&&!confirm(t('切换并放弃未保存的修改？'))){event.target.value=current?.id||'';return;}try{const revision=++selectionRevision;if(!event.target.value){current=null;canvas.set(template());return;}const loaded=await api.request(`${base}/${event.target.value}`);if(disposed||revision!==selectionRevision)return;current=loaded;canvas.set(current.graph||current.draft_graph);dirty=false;$('#workflowName',host).value=current.name;$('#draftState',host).textContent=current.published_version_id?t('草稿 · 已有发布版'):t('草稿已保存');await history();}catch(error){toast(error.message,'error');}};
  host.querySelectorAll('[data-type]').forEach(button=>{button.onclick=()=>canvas.add(button.dataset.type);button.ondragstart=event=>event.dataTransfer.setData('application/x-node-type',button.dataset.type);});
  $('#publishedRun',host).checked=!editable;$('#publishedRun',host).disabled=!editable;$('#graphTemplate',host).disabled=!editable;$('#workflowName',host).readOnly=!editable;$('#undoGraph',host).disabled=!editable;$('#redoGraph',host).disabled=!editable;
  $('#runForm',host).onsubmit=async event=>{event.preventDefault();if(running)return;const query=new FormData(event.target).get('query'),control=new AbortController();running=control;$('#runButton',host).disabled=true;$('#cancelRun',host).hidden=false;$('#cancelRun',host).disabled=false;$('#workflowSelect',host).disabled=true;$('#newWorkflow',host).disabled=true;$('#runStatus',host).textContent=t('正在启动');try{if(!current||dirty)await save();if(dirty)throw new Error(t('草稿在保存期间有修改，请再次保存后运行'));const run=await runWorkflow(api,current.id,{query,use_published:$('#publishedRun',host).checked},{signal:control.signal,onUpdate:value=>{if(!disposed)showRun(value);}});if(!disposed){showRun(run);await history().catch(()=>toast(t("已收到运行结果，暂时无法刷新历史记录。"),"error"));}}catch(error){if(!disposed){$('#runStatus',host).textContent=error.name==='AbortError'?t('已取消启动'):error.runId||!error.status?t('状态未确认'):t('启动失败');toast(error.runId?t('连接中断，运行状态尚未确认。请刷新运行记录。'):error.message,'error');}}finally{running=null;if(!disposed){$('#runButton',host).disabled=false;$('#cancelRun',host).hidden=true;$('#workflowSelect',host).disabled=false;$('#newWorkflow',host).disabled=!editable;}}};$('#cancelRun',host).onclick=()=>{running?.abort();$('#cancelRun',host).disabled=true;$('#runStatus',host).textContent=t('正在请求取消');};
  return()=>{disposed=true;running?.abort();canvas.dispose();};
}
